### ISSUE TITLE
Is the login working for you?

### ISSUE THREAD

**Issue by MichaelStephan** [theasp/sente-nodejs-example#1]
Hello,

I'm currently exploring your project. Does the login with express work for you? Whenever I try the login it seems that the connection is re-established with :uid set to :taoensso.sente/nil-uid.

Cheers,
Michael

**Comment by MichaelStephan** [comment]
I created a pull request fixing the issue.

**Comment by theasp** [comment]
Thanks, i hadn't noticed this, I don't use uid myself.  #2 is merged.
